package xyz.illuc.neuralgiacore.entities;

import net.minecraft.world.entity.ai.attributes.AttributeSupplier;
import net.minecraft.world.entity.ai.attributes.Attributes;
import net.minecraftforge.event.entity.EntityAttributeCreationEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;
import xyz.illuc.neuralgiacore.NeuralgiaCoreMod;

@Mod.EventBusSubscriber(bus = Mod.EventBusSubscriber.Bus.MOD)
public class OfflinePlayerAttributes {
    @SubscribeEvent //gleeked out
    public static void newEntityAttributes(EntityAttributeCreationEvent event) {
        event.put(
                NeuralgiaCoreMod.GHOST.get(),
                net.minecraft.world.entity.LivingEntity.createLivingAttributes()
                        .add(Attributes.MAX_HEALTH, 20.0D)
                        .build()
        );
    }
}
